#pragma once

#define SUCCESS_LOGIN "10"
#define FAILED_LOGIN "11"
#define SUCCESS_LOGOUT "20"
#define FAILED_LOGOUT "21"
#define SUCCESS_SHOW_ROOM "30"
#define SUCCESS_JOIN_ROOM "40"
#define ROOM_CLOSED "41"
#define SUCCESS_BID "50"
#define LOWER_THAN_CURRENT_PRICE "51"
#define CREATOR_CANT_BID "52"
#define SUCCESS_BUY_IMMEDIATELY "60"
#define ALREADY_SOLD "61"
#define CREATOR_CANT_BUY "62"
#define SUCCESS_CREATE_ROOM "70"
#define INVALID_INFORMATION "71"
#define ITEM_SOLD_NOTIFICATION "80"
#define TIME_NOTIFICATION "81"
#define NEW_PRICE_NOTIFICATION "82"
#define ROOM_ID_NOT_FOUND "83"
#define SUCCESS_LEAVE_ROOM "90"
#define MAX_CLIENT 1024
#define MAX_ROOM 1024
#define ENDING_DELIMITER "\r\n"
#define SPLITING_DELIMITER_1 "\t\n"
#define SPLITING_DELIMITER_2 "\f\n"
#define BUFF_SIZE 2048


