#pragma once

#define SUCCESS_LOGIN "10"
#define FAILED_LOGIN "11"
#define SUCCESS_LOGOUT "20"
#define FAILED_LOGOUT "21"
#define SUCCESS_SHOW_ROOM "30"
#define SUCCESS_JOIN_ROOM "40"
#define ROOM_NOT_FOUND "41"
#define SUCCESS_BID "50"
#define LOWER_THAN_CURRENT_PRICE "51"
#define SUCCESS_BUY_IMMEDIATELY "60"
#define ALREADY_SOLD "60"
#define SUCCESS_CREATE_ROOM "70"
#define INVALID_INFORMATION "71"
#define MAX_CLIENT 1024
#define MAX_ROOM 1024
#define ENDING_DELIMITER "\r\n"
#define SPLITING_DELIMITER_1 "\t\n"
#define SPLITING_DELIMITER_2 "\y\n"
#define BUFF_SIZE 2048


